FROM mcr.microsoft.com/mssql/server:2017-latest

WORKDIR /usr/src/app
COPY . /usr/src/app

#  Grant permissions for the import script to be executable
RUN chmod +x /usr/src/app/import.sh
RUN chmod +x /usr/src/app/entrypoint.sh


CMD /bin/bash /usr/src/app/entrypoint.sh
